name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/setup@v2
        with:
          runtime: node@24
          require-lockfile: true
          cache: true
      - run: pnpm test
      - run: pnpm check
